README.md
There is store application with usage of AngularJS

Setup environment:
for better expirienc - you have to use git bash - https://git-scm.com/downloads
run in git bash next sequence of commands
1.  git clone https://github.com/vitto-moz/testStore_app.git
2.  cd testStore_app
3.  npm install (nodejs with npm required)
4.  gulp serve
5. go to localhost mentioned in command line (bash) in your browser

if error below occure (during "gulp serve" run) - 
    gulptnst.start.applylgulplnst. toRun);
    ^
    TypeError: Cannot read property 'apply' of undefined

run command: "npm install -g gulp-cli"